Repository F5-Refresh/payhere, pull requests merged in 2022-07, with the labels that each got.

#16 [김동규] #8-유저 회원가입 기능 구현
  account_books/migrations/0001_initial.py
  payhere/settings.py
  requirements.txt
  users/migrations/0001_initial.py
  users/serializers.py
  users/urls.py
  users/views.py
  users/views/sign.py
Labels: develop

#17 [김동규] #8-fix-bcrypt 라이브러리 추가
  requirements.txt
Labels: develop

#19 [조병민] #10 로그인, 로그아웃 test 작성
  users/serializers.py
  users/tests.py
  users/views/sign.py
Labels: test

#18 [김동규] #9-유저 회원가입 API 테스트코드 작성
  users/tests.py
Labels: test

#20 [이동연] #11 카테고리 CRUD작성
  account_books/migrations/0001_initial.py
  account_books/migrations/0002_accountcategory_delete_flag.py
  account_books/models.py
  account_books/serializers.py
  account_books/tests.py
  account_books/urls.py
  account_books/views.py
  account_books/views/account_category_views.py
  core/util.py
  payhere/settings.py
  payhere/urls.py
Labels: develop

#13 [전기원] #7 가계부 리스트, 생성, 수정, 삭제리스트 구현
  account_books/models.py
  account_books/serializers.py
  account_books/tests.py
  account_books/urls.py
  account_books/views/account_book_views.py
  payhere/urls.py
Labels: develop

#21 [이동연] #11 카테고리 CRUD작성
  account_books/tests.py
  payhere/test_models.py
Labels: develop

#23 [김동규] #9 테스트코드 예외처리 메세지 수정
  users/tests.py
Labels: develop

#24 [김동규] #9 테스트 파일 디렉토리 구조 수정 및 코드 컨벤션 수정
  users/tests/__init__.py
  users/tests/tests_signup.py
  users/views/sign.py
Labels: develop

#14 [남효정] #6 가계부 내역 C R U D 구현 및 테스트 코드 작성
  account_books/admin.py
  account_books/migrations/0001_initial.py
  account_books/migrations/0002_accountcategory_delete_flag.py
  account_books/migrations/0002_alter_accountdetail_account_type.py
  account_books/migrations/0003_alter_accountdetail_account_type.py
  account_books/migrations/0004_alter_accountdetail_account_book.py
  account_books/models.py
  account_books/serializers.py
  account_books/tests/test_account_books_detail.py
  account_books/tests/tests.py
  account_books/urls.py
  account_books/views/account_book_detail_views.py
  account_books/views/account_category_views.py
  core/util.py
  users/admin.py
Labels: develop

#30 [김동규] #29 배포를 위한 설정파일 추가 및 Swagger 설정 파일 추가
  config/nginx/nginx.conf
  docker-compose.yml
  dockerfile
  payhere/settings.py
  payhere/urls.py
Labels: develop

#5 [이동연] #1-프로젝트 초기세팅
  .gitignore
  account_books/__init__.py
  account_books/admin.py
  account_books/apps.py
  account_books/migrations/0001_initial.py
  account_books/migrations/0002_alter_accountdetail_account_type.py
  account_books/migrations/0003_alter_accountdetail_account_type.py
  account_books/migrations/0004_alter_accountdetail_account_book.py
  account_books/migrations/__init__.py
  account_books/models.py
  account_books/serializers.py
  account_books/tests/__init__.py
  account_books/tests/test_account_books.py
  account_books/tests/test_account_books_detail.py
  account_books/tests/test_acount_category.py
  account_books/tests/tests.py
  account_books/urls.py
  account_books/views/account_book_detail_views.py
  account_books/views/account_book_views.py
  account_books/views/account_category_views.py
  config/nginx/nginx.conf
  core/__init__.py
  core/admin.py
  core/apps.py
  core/migrations/__init__.py
  core/models.py
  core/tests.py
  core/util.py
  core/views.py
  docker-compose.yml
  dockerfile
  manage.py
  payhere/__init__.py
  payhere/asgi.py
  payhere/settings.py
  payhere/test_models.py
  payhere/urls.py
  payhere/wsgi.py
  requirements.txt
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
  users/models.py
  users/serializers.py
  users/tests/__init__.py
  users/tests/tests_UserSignInOutTest.py
  users/tests/tests_signup.py
  users/urls.py
  users/views/sign.py
Labels: initialized
